#!/usr/bin/env bash
# The ratchet on catalog knowledge in the builder's main sources.
#
# Every string literal that names a catalog other than the packaged floor (`m3/*`, `layout/*`,
# `m3-catalog`) is a fact some catalog repository should be publishing instead — a component id the
# builder recognises, a system id it branches on. `UI_BUILDER_CATALOG_CONTRACT.md` § Success
# criteria wants none; this holds the line on the way there. `.github/catalog-id-allowlist.txt`
# records how many each file has, and must match EXACTLY, like the readiness test's gap ledger:
#
#   - a file that gains one fails, so new knowledge is a reviewed decision rather than drift;
#   - a file that loses one also fails, until the allowlist is lowered, so a deletion is recorded
#     and cannot quietly be spent on the next addition.
#
#   .github/scripts/catalog-id-ratchet.sh            # check
#   .github/scripts/catalog-id-ratchet.sh --update   # rewrite the allowlist to the current counts
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
allowlist="${root}/.github/catalog-id-allowlist.txt"

# A literal opening with a non-floor catalog's namespace or system id.
pattern='"(wear-m3|remote-m3|remote-widgets|a2ui|a2ui-catalog|glimmer|glimmer-catalog)(/|")'

current="$(
  cd "${root}"
  git ls-files -- '*/src/*Main/*.kt' '*/src/main/*.kt' |
    while IFS= read -r file; do
      count="$(grep -oE "${pattern}" "${file}" | wc -l | tr -d ' ')"
      [[ "${count}" == 0 ]] || printf '%s %s\n' "${count}" "${file}"
    done |
    sort -k2
)"

if [[ "${1:-}" == "--update" ]]; then
  {
    echo "# Catalog-id literals per main-source file. Generated by .github/scripts/catalog-id-ratchet.sh"
    echo "# --update; the check fails on any difference, in either direction. Lower it, never raise it"
    echo "# without saying in the PR why the builder has to know this catalog's id."
    printf '%s\n' "${current}"
  } >"${allowlist}"
  echo "rewrote ${allowlist#"${root}/"} ($(printf '%s\n' "${current}" | awk '{s+=$1} END {print s+0}') literals)"
  exit 0
fi

expected="$(grep -v '^#' "${allowlist}" | sed '/^$/d' | sort -k2)"
if [[ "${current}" == "${expected}" ]]; then
  echo "catalog-id ratchet: $(printf '%s\n' "${current}" | awk '{s+=$1} END {print s+0}') literals, as recorded"
  exit 0
fi

echo "catalog-id ratchet: main sources differ from .github/catalog-id-allowlist.txt" >&2
diff <(printf '%s\n' "${expected}") <(printf '%s\n' "${current}") |
  sed -n 's/^< /  recorded: /p; s/^> /  now:      /p' >&2
cat >&2 <<'MSG'

A count that went DOWN: well done; run `.github/scripts/catalog-id-ratchet.sh --update` and commit it.
A count that went UP, or a new file: the builder learned a catalog's id. Prefer a catalog-published
fact (a `CatalogBuilderRoles` trait, `insertContent`, a property `editor`, the policy file); if the
id really is needed, run --update and say why in the PR.
MSG
exit 1
