#!/usr/bin/env python3
"""Writes LcdGlyphs.kt: glyph outlines for the LCD watch replica preview, as Kotlin data.

A RemoteCanvas cannot load a font, so the replica draws its type as paths. This reads three fonts,
all under the SIL Open Font License 1.1:

- DSEG7 Classic Bold Italic and DSEG14 Classic Bold Italic, by keshikan
  (https://github.com/keshikan/DSEG): the LCD's seven- and fourteen-segment cells. Each lit segment
  of a DSEG glyph is its own contour, so the segments are read off one by one and named by where
  they sit, and the replica lights each from a formula over the clock.
- Michroma, by the Michroma Project Authors (https://github.com/googlefonts/Michroma-font): the
  face printing, the free face nearest the Microgramma/Eurostile Extended the watch is printed in.

Usage: generate.py DSEG7Classic-BoldItalic.ttf DSEG14Classic-BoldItalic.ttf Michroma-Regular.ttf OUT.kt
"""
import sys
from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import DecomposingRecordingPen

LABELS = ["PM", "F-91W", "LIGHT", "ALARM CHRONOGRAPH", "MODE", "ALARM ON·OFF/24HR", "WATER", "WR", "RESIST"]
DAY_LETTERS = sorted(set("MOTUWETHFRSASU"))


def contours(font, name):
    glyphs = font.getGlyphSet()
    pen = DecomposingRecordingPen(glyphs)
    glyphs[name].draw(pen)
    out, current, last = [], [], None
    for op, args in pen.value:
        if op == "moveTo":
            current = [args[0]]
            last = args[0]
        elif op == "lineTo":
            current.append(args[0])
            last = args[0]
        elif op == "qCurveTo":
            # Expand the implied on-curve points, then flatten each quadratic into a few lines.
            pts = list(args)
            on = pts[-1]
            offs = pts[:-1]
            segs = []
            for i, c in enumerate(offs):
                end = on if i == len(offs) - 1 else ((c[0] + offs[i + 1][0]) / 2, (c[1] + offs[i + 1][1]) / 2)
                segs.append((c, end))
            for c, end in segs:
                for k in range(1, 5):
                    t = k / 4
                    x = (1 - t) ** 2 * last[0] + 2 * (1 - t) * t * c[0] + t * t * end[0]
                    y = (1 - t) ** 2 * last[1] + 2 * (1 - t) * t * c[1] + t * t * end[1]
                    current.append((x, y))
                last = end
        elif op == "curveTo":
            c1, c2, end = args
            for k in range(1, 7):
                t = k / 6
                u = 1 - t
                x = u**3 * last[0] + 3 * u * u * t * c1[0] + 3 * u * t * t * c2[0] + t**3 * end[0]
                y = u**3 * last[1] + 3 * u * u * t * c1[1] + 3 * u * t * t * c2[1] + t**3 * end[1]
                current.append((x, y))
            last = end
        elif op in ("closePath", "endPath"):
            if current:
                out.append(current)
            current = []
    return out


def centroid(c):
    return (sum(p[0] for p in c) / len(c), sum(p[1] for p in c) / len(c))


def glyph_name(font, ch):
    return font.getBestCmap()[ord(ch)]


def kt_points(points, scale, ox, oy):
    # x right, y down, in units of the cell height (or em, for type).
    return "doubleArrayOf(" + ", ".join(
        f"{round((x - ox) * scale, 4)}, {round((oy - y) * scale, 4)}" for x, y in points
    ) + ")"


def main(seven_path, fourteen_path, michroma_path, out_path):
    seven = TTFont(seven_path)
    fourteen = TTFont(fourteen_path)
    michroma = TTFont(michroma_path)
    lines = []
    emit = lines.append
    emit("// Generated by scripts/watch-glyphs/generate.py — do not edit by hand.")
    emit("//")
    emit("// Outlines from DSEG7 Classic and DSEG14 Classic (Bold Italic) by keshikan, and Michroma by")
    emit("// the Michroma Project Authors, all under the SIL Open Font License 1.1.")
    emit("package ee.schimke.composeai.uibuilder.preview")
    emit("")
    emit("/** Glyph outlines for [lcdWatchReplica]; see scripts/watch-glyphs/generate.py. */")
    emit("internal object LcdGlyphs {")

    # Seven segments, from "8": name each contour by where its centre sits.
    eight = contours(seven, glyph_name(seven, "8"))
    xs = [p[0] for c in eight for p in c]
    ys = [p[1] for c in eight for p in c]
    top, bottom, left = max(ys), min(ys), min(xs)
    height = top - bottom
    scale = 1 / height
    adv = seven["hmtx"][glyph_name(seven, "8")][0]
    named = {}
    for c in eight:
        cx, cy = centroid(c)
        v = (top - cy) / height
        w = max(p[0] for p in c) - min(p[0] for p in c)
        h = max(p[1] for p in c) - min(p[1] for p in c)
        mid_x = (min(xs) + max(xs)) / 2 + 0.0
        if w > h:  # horizontal
            name = "a" if v < 0.25 else ("g" if v < 0.75 else "d")
        else:
            upper = v < 0.5
            # The cell is italic, so compare against the cell's centre line at this height.
            slant_mid = mid_x + (cy - (top + bottom) / 2) * ((max(xs) - min(xs)) / height) * 0.12
            is_left = cx < slant_mid
            name = ("f" if is_left else "b") if upper else ("e" if is_left else "c")
        named[name] = c
    assert sorted(named) == list("abcdefg"), sorted(named)
    emit("  /** DSEG7 Classic Bold Italic: each segment, x right and y down, in cell heights. */")
    emit("  val SEVEN: Map<Char, DoubleArray> = mapOf(")
    for k in "abcdefg":
        emit(f"    '{k}' to {kt_points(named[k], scale, left, top)},")
    emit("  )")
    emit(f"  /** The seven-segment cell's width, in cell heights, as \"8\" advances. */")
    emit(f"  const val SEVEN_ADVANCE: Double = {round(adv * scale, 4)}")
    colon = contours(seven, glyph_name(seven, ":"))
    emit("  /** The two dots of DSEG7's colon, in the same units. */")
    emit("  val COLON: List<DoubleArray> = listOf(")
    for c in colon:
        emit(f"    {kt_points(c, scale, left, top)},")
    emit("  )")
    emit(f"  const val COLON_ADVANCE: Double = {round(seven['hmtx'][glyph_name(seven, ':')][0] * scale, 4)}")

    # Fourteen segments: pool every distinct contour the day letters use, so unlit ones can ghost.
    pool, letters = [], {}
    for ch in DAY_LETTERS + ["8"]:
        ids = []
        for c in contours(fourteen, glyph_name(fourteen, ch)):
            key = tuple(round(v) for v in centroid(c))
            match = next((i for i, (k, _) in enumerate(pool) if abs(k[0] - key[0]) < 6 and abs(k[1] - key[1]) < 6), None)
            if match is None:
                pool.append((key, c))
                match = len(pool) - 1
            ids.append(match)
        letters[ch] = sorted(set(ids))
    fx = [p[0] for _, c in pool for p in c]
    fy = [p[1] for _, c in pool for p in c]
    ftop, fbottom, fleft = max(fy), min(fy), min(fx)
    fscale = 1 / (ftop - fbottom)
    emit("  /** DSEG14 Classic Bold Italic: every segment the day letters use, in cell heights. */")
    emit("  val FOURTEEN: List<DoubleArray> = listOf(")
    for _, c in pool:
        emit(f"    {kt_points(c, fscale, fleft, ftop)},")
    emit("  )")
    emit("  /** Which of [FOURTEEN] each day letter lights. */")
    emit("  val FOURTEEN_LETTERS: Map<Char, Set<Int>> = mapOf(")
    for ch in DAY_LETTERS:
        emit(f"    '{ch}' to setOf({', '.join(map(str, letters[ch]))}),")
    emit("  )")
    emit(f"  const val FOURTEEN_ADVANCE: Double = {round(fourteen['hmtx'][glyph_name(fourteen, 'M')][0] * fscale, 4)}")

    # Michroma: each label as contours in ems, baseline at y = 0, with its width.
    upem = michroma["head"].unitsPerEm
    cmap = michroma.getBestCmap()
    hmtx = michroma["hmtx"]
    emit("  /** Michroma: each label's contours in ems, x from its start, y down from the baseline. */")
    emit("  val TYPE: Map<String, Pair<Double, List<DoubleArray>>> = mapOf(")
    for label in LABELS:
        x = 0
        cs = []
        for ch in label:
            name = cmap.get(ord(ch))
            if name is None:
                x += upem * 0.3
                continue
            for c in contours(michroma, name):
                cs.append([(px + x, py) for px, py in c])
            x += hmtx[name][0]
        body = ", ".join(kt_points(c, 1 / upem, 0, 0) for c in cs)
        emit(f"    \"{label}\" to ({round(x / upem, 4)} to listOf({body})),")
    emit("  )")
    emit("}")
    open(out_path, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(*sys.argv[1:5])
