package ee.schimke.composeai.uibuilder.service

/**
 * The published files [PublishedUiBuilderCatalog]'s equivalence tests compose, as one captured set.
 *
 * These are test resources under `published-catalog/`, NOT the repository's
 * `docs/design/fixtures/ui-builder/` files, on purpose. Each test asserts the composition of three
 * files at once (a catalog's published policy, the component record it joins, and the frozen
 * catalog it must reproduce), and the three only agree when they were captured together. The
 * documentation fixtures move on their own schedules: the frozen catalogs are regenerated by
 * `SynthesisedCatalogGoldenTest`, the record by the export codegen, the published policy by the
 * catalog producer's CI. Reading them here would turn every one of those changes into a red test
 * about a composition nobody changed.
 *
 * The set came with the composer from compose-preview-server, where these tests lived until the
 * composer moved into this module, so the server no longer pins this repository's behaviour in its
 * own tests. Re-capturing it is a reviewed change like any golden: copy the current files in and
 * read the assertions' diff.
 */
internal const val PUBLISHED_CATALOG_FIXTURES: String = "/published-catalog/"

internal fun publishedCatalogFixture(name: String): String =
  checkNotNull(
      PublishedUiBuilderCatalog::class.java.getResource(PUBLISHED_CATALOG_FIXTURES + name)
    ) {
      "missing test resource $PUBLISHED_CATALOG_FIXTURES$name"
    }
    .readText()
