import java.io.File
import java.util.Properties
import java.util.zip.ZipFile

plugins {
  `java-library`
}

group = "ee.schimke.composeai"

val publishedArtifactId = "compose-preview-ui-builder-render-bundle"

/**
 * The packaged UI-builder render bundle, as an artifact of its own.
 *
 * ## Why this is not a resource in `:ui-builder-runtime`
 *
 * It was one, and the edge pointed the wrong way. `:ui-builder-runtime` is server-side and
 * published; the bundle is a *frontend* build output — a polyglot PNG whose embedded ZIP carries
 * `:ui-builder`'s compiled JVM previews and their minimal classpath. A published server jar
 * carrying the frontend's class files had two costs. It made `:ui-builder-runtime` depend on
 * `:ui-builder`'s build, which a repository split cannot carry across a boundary
 * ([#346](https://github.com/yschimke/compose-preview-server/issues/346)); and it pinned the
 * frontend's JVM target to the server's, because those class files ship inside the server's
 * artifact and every consumer of it has to be able to load them.
 *
 * This module owns the packaging instead. It sits on the frontend side of that line, exactly as
 * `:ui-builder-web` does for `wasmDist`, so `:ui-builder-runtime` reaches the bundle through a
 * coordinate — the one thing that survives a repository boundary.
 *
 * ## Why a jar and not a distribution archive
 *
 * `:ui-builder-web` publishes a Zip with distribution attributes because its consumer unpacks it
 * into a served directory. This one's consumer is `PackagedUiBuilderRenderBundle.copyTo`, which
 * reads `getResourceAsStream`. A classpath lookup does not care *which* jar answers it, so
 * shipping the bundle as an ordinary resource in a sibling jar leaves that public API — and every
 * caller of it — byte-for-byte unchanged, while moving the bytes out of the runtime's own artifact.
 *
 * ## Why there is no source set
 *
 * Deliberately none, and it is the point: a module that compiles nothing has no JVM target to
 * inherit or impose. The frontend can move its own toolchain without this artifact acquiring an
 * opinion about the server's.
 */
version =
  providers.environmentVariable("PLUGIN_VERSION").orNull
    ?: run {
      val current =
        Regex(""""\.":\s*"([^"]+)"""")
          .find(rootDir.resolve(".release-please-manifest.json").readText())!!
          .groupValues[1]
      val (major, minor, patch) = current.split(".").map { it.toInt() }
      "$major.$minor.${patch + 1}-SNAPSHOT"
    }

base { archivesName.set(publishedArtifactId) }

/**
 * The resource path is the contract.
 *
 * `PackagedUiBuilderRenderBundle.RESOURCE` names this exact path and is public API of
 * `compose-preview-ui-builder-runtime`. Moving the bytes between artifacts is invisible to a
 * consumer precisely as long as the path does not move with them, so the two are pinned together
 * by `UiBuilderRenderBundleResourcePathTest` in that module rather than by hope.
 */
val bundleResourceDirectory = "ee/schimke/composeai/uibuilder/renderer"

val bundleResourceName = "ui-builder-renderer.bundle.png"

/**
 * The bundle's Java floor, shipped beside the bundle as data.
 *
 * The polyglot carries `:ui-builder`'s compiled JVM previews, and `:ui-builder` compiles at
 * `java-ui-builder` — above the floor of every artifact that reaches a consumer. That is legal
 * precisely because these bytes are opaque until a render daemon unpacks them, but the daemon runs
 * under the *server's* JVM (`java.home`), so a host below the floor gets an
 * `UnsupportedClassVersionError` from a process it did not know existed
 * ([#344](https://github.com/yschimke/compose-preview-server/issues/344)).
 *
 * The number is written here rather than duplicated in the server because this module is the one
 * that knows it: it is the same catalog entry `:ui-builder`'s toolchain reads, so raising that
 * toolchain moves the preflight with it and cannot leave it behind.
 */
val bundleManifestResourceName = "ui-builder-renderer.bundle.properties"

val bundleJavaMin = libs.versions.java.ui.builder.get().toInt()

val writeBundleManifest =
  tasks.register("writeBundleManifest") {
    description = "Write the render bundle's Java floor as a resource beside the bundle."
    val manifest =
      layout.buildDirectory.file("generated/bundle-manifest/$bundleManifestResourceName")
    val javaMin = bundleJavaMin
    inputs.property("javaMin", javaMin)
    outputs.file(manifest)
    doLast {
      manifest
        .get()
        .asFile
        .also { it.parentFile.mkdirs() }
        .writeText(
          buildString {
            appendLine("# Generated by :ui-builder-render-bundle:writeBundleManifest. Do not edit.")
            appendLine("# The Java feature version required to load the classes inside the bundle.")
            appendLine("javaMin=$javaMin")
          }
        )
    }
  }

// The same shape `:ui-builder-runtime` used when it owned these bytes, moved rather than rewritten:
// a `processResources` copy out of `:ui-builder`'s build directory, which this build already proves
// works under the configuration cache. This module has no other resource and no source at all, so
// the copy is the whole of its jar.
tasks.processResources {
  // Locals, not the script properties directly: a `rename` transformer is serialized into the
  // configuration cache, and a lambda reading a script-level `val` captures the whole script object
  // with it — which the cache refuses. Copying the two strings here captures two strings.
  val resourceDirectory = bundleResourceDirectory
  val resourceName = bundleResourceName
  dependsOn(project(":ui-builder").tasks.named("composePreviewBundle"))
  from(project(":ui-builder").layout.buildDirectory.file("compose-previews/bundle.png")) {
    into(resourceDirectory)
    rename { resourceName }
  }
  from(writeBundleManifest) { into(resourceDirectory) }
}

/**
 * A jar that silently lost its only reason to exist is worse than a build failure.
 *
 * `composePreviewBundle` is a render-producing task in another module; a configuration change that
 * left it out, or a rename of the file it writes, would otherwise publish an empty artifact and
 * fail at a consumer's runtime with "packaged UI-builder renderer bundle is missing".
 */
val verifyRenderBundlePackaged =
  tasks.register("verifyRenderBundlePackaged") {
    description = "Fail the build if the published jar does not carry the render bundle."
    group = "verification"
    val jarFile = tasks.named<Jar>("jar").flatMap { it.archiveFile }
    // Locals for the same reason the copy above takes them: a `doLast` action is cached, and
    // reading `publishedArtifactId` straight from the script would drag the script into the cache.
    val entry = "$bundleResourceDirectory/$bundleResourceName"
    // The manifest is checked beside the bundle rather than separately: a jar carrying the preview
    // without its Java floor turns the server's preflight into a hard failure on a host that could
    // have run it, which is a worse outcome than the missing diagnostic it was added to replace.
    val manifestEntry = "$bundleResourceDirectory/$bundleManifestResourceName"
    val artifactId = publishedArtifactId
    // A local, so the `doLast` lambda captures a List<String>. Reading a script-level `val` from
    // inside it captures the whole script object, which the configuration cache refuses -- the
    // same trap the `processResources` block above takes locals to avoid, which I walked into
    // anyway.
    //
    // Coordinates the RENDERER needs that no packed preview reaches.
    // `androidx.window.core.layout.WindowSizeClass` is imported by `UiBuilderRenderer.kt` and
    // called from `AdaptiveSupportingPaneScaffold`, which the node renderer enters for a
    // `layout/supporting-pane-scaffold` node -- needed by the *document*, never by the one preview
    // the bundle packs (#788 introduced the call, #812 is the 500 it produced).
    //
    // Matched against the KMP variant suffixes too: a multiplatform module publishes a root
    // coordinate that redirects (`available-at`) to a per-platform artifact, so the resolved JVM
    // dependency is recorded as `window-core-desktop`, never `window-core`. An exact match here
    // failed on a bundle that carried the class perfectly well.
    val required = listOf("org.jetbrains.androidx.window:window-core")
    val variantSuffixes = listOf("", "-desktop", "-jvm")
    inputs.file(jarFile)
    doLast {
      ZipFile(jarFile.get().asFile).use { jar ->
        val packaged = checkNotNull(jar.getEntry(entry)) { "$artifactId does not carry $entry" }
        check(packaged.size > 0) { "$artifactId carries an empty $entry" }
        val manifest =
          checkNotNull(jar.getEntry(manifestEntry)) { "$artifactId does not carry $manifestEntry" }
        val javaMin =
          jar.getInputStream(manifest).use { stream ->
            Properties().apply { load(stream) }.getProperty("javaMin")
          }
        checkNotNull(javaMin?.toIntOrNull()) { "$manifestEntry has no numeric javaMin" }

        // The bundle's own classpath, checked for the render-only coordinates below.
        //
        // `composePreviewBundle` minimizes: a dependency with no class reachable from the packed
        // preview is dropped, and `bundle.json` lists only what survived. That is correct for a
        // library the previews never touch and silent for one the RENDERER reaches only when a
        // rendered document asks for it -- nothing fails until a design uses the component, and
        // then it is a 500 from `exportDesign` naming a bare class, a long way from this build.
        val bundleFile = File.createTempFile("ui-builder-renderer", ".bundle")
        try {
          jar.getInputStream(packaged).use { source ->
            bundleFile.outputStream().use { sink -> source.copyTo(sink) }
          }
          // The bundle is a polyglot PNG whose tail is an ordinary zip, which is how the daemon
          // opens it too.
          val carried =
            ZipFile(bundleFile).use { bundle ->
              val descriptor =
                checkNotNull(bundle.getEntry("bundle.json")) { "$entry carries no bundle.json" }
              val parsed =
                bundle.getInputStream(descriptor).use { stream ->
                  groovy.json.JsonSlurper().parseText(stream.readBytes().toString(Charsets.UTF_8))
                }
              @Suppress("UNCHECKED_CAST")
              val classpath =
                ((parsed as Map<String, Any?>)["classpath"] as? List<Map<String, Any?>>).orEmpty()
              // `kind`, not `type`. `BundlePreviewTask` serializes these with
              // `classDiscriminator = "kind"`, and a Maven entry carries its OWN `type` field
              // holding the packaging -- so filtering on `type` matches "jar", never "maven",
              // and the set comes back empty.
              classpath
                .filter { it["kind"] == "maven" }
                .map { "${it["group"]}:${it["artifact"]}" }
                .toSet()
            }
          check(carried.isNotEmpty()) { "$entry lists no Maven coordinates; the check is vacuous" }
          val missing =
            required.filterNot { coordinate ->
              variantSuffixes.any { suffix -> "$coordinate$suffix" in carried }
            }
          check(missing.isEmpty()) {
            "the render bundle does not carry ${missing.joinToString()}. " +
              "`:ui-builder` imports classes from it, so the daemon renders without them and an " +
              "export of any document that reaches them fails with a bare class name. Likely " +
              "`composePreviewBundle` pruned it as unreachable -- but check the carried list " +
              "first for a variant spelling this assertion does not know about. " +
              "Carried: ${carried.sorted().joinToString()}"
          }
        } finally {
          bundleFile.delete()
        }
      }
    }
  }

tasks.named("check") { dependsOn(verifyRenderBundlePackaged) }

