package ee.schimke.composeai.uibuilder.export

import ee.schimke.composeai.uibuilder.export.VariableFontText.Font
import ee.schimke.composeai.uibuilder.export.VariableFontText.Spec
import ee.schimke.composeai.uibuilder.export.VariableFontText.Target
import ee.schimke.composeai.uibuilder.export.VariableFontText.of
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

class VariableFontTextTest {
  private fun spec(
    text: String = "Flex",
    font: Font = Font.RobotoFlex,
    animated: List<String> = listOf("wght"),
    location: Map<String, Float> = emptyMap(),
    target: Target = Target.COMPOSE_UI,
  ) = Spec(font, text, animated, location, target)

  @Test
  fun `a name reads the font, the text and the animated axes`() {
    val requests = VariableFontText.requests(listOf(spec(animated = listOf("wght", "wdth"))))
    assertEquals("VariableFontTextRobotoFlexFlexWghtWdth", requests.single().functionName)
    assertEquals(
      "VariableFontTextGoogleSansFlexHelloWorldRond",
      VariableFontText.requests(
          listOf(spec("hello, world!", Font.GoogleSansFlex, animated = listOf("ROND")))
        )
        .single()
        .functionName,
    )
  }

  @Test
  fun `text that is no identifier is named Text, and long text is cut at a word`() {
    assertEquals(
      "VariableFontTextRobotoFlexTextWght",
      VariableFontText.requests(listOf(spec("→ ✓"))).single().functionName,
    )
    val long = VariableFontText.requests(listOf(spec("a very long line of text to draw"))).single()
    assertEquals("VariableFontTextRobotoFlexAVeryLongLineOfTextToWght", long.functionName)
    val word =
      VariableFontText.requests(listOf(spec("Supercalifragilisticexpialidocious"))).single()
    assertEquals("VariableFontTextRobotoFlexSupercalifragilisticexpiWght", word.functionName)
  }

  @Test
  fun `identical specs share a request and colliding names are numbered`() {
    val bold = spec(location = mapOf("wdth" to 75f))
    val wide = spec(location = mapOf("wdth" to 151f))
    val requests = VariableFontText.requests(listOf(bold, wide, bold))
    assertEquals(2, requests.size)
    assertEquals("VariableFontTextRobotoFlexFlexWght", requests.of(bold).functionName)
    assertEquals("VariableFontTextRobotoFlexFlexWght_2", requests.of(wide).functionName)
  }

  @Test
  fun `an axis the font does not offer, an axis set twice and empty text are problems`() {
    assertEquals(emptyList(), VariableFontText.problems(spec(location = mapOf("slnt" to -5f))))
    assertEquals(
      listOf("Roboto Flex has no rond axis a design can set"),
      VariableFontText.problems(spec(animated = listOf("ROND"))),
    )
    assertEquals(
      listOf("the wght axis is both animated and held"),
      VariableFontText.problems(spec(location = mapOf("wght" to 700f))),
    )
    assertEquals(listOf("variable font text needs some text"), VariableFontText.problems(spec("")))
  }

  @Test
  fun `fonts are found by wire name and axes by property`() {
    assertEquals(Font.GoogleSansFlex, Font.fromWire("googleSansFlex"))
    assertNull(Font.fromWire("Google Sans Flex"))
    assertEquals("ROND", Font.GoogleSansFlex.axis("rond")?.tag)
    assertNull(Font.RobotoFlex.axis("rond"))
    assertEquals(listOf("wght", "wdth", "slnt", "rond"), VariableFontText.AXIS_PROPERTIES)
  }

  @Test
  fun `joined files keep one package, every import once, and each file's declarations`() {
    val main =
      """
      |// Screen.kt
      |package generated.uibuilder
      |
      |import androidx.compose.runtime.Composable
      |import androidx.compose.ui.unit.sp
      |
      |@Composable fun Screen() { A(fontSize = 1.sp) }
      |"""
        .trimMargin()
    val companion =
      """
      |// Generated by VariableFontCodegen: "Flex".
      |// Do not edit.
      |
      |package generated.uibuilder
      |
      |import androidx.compose.runtime.Composable
      |import androidx.compose.ui.graphics.Color
      |
      |@Composable internal fun A(fontSize: TextUnit, color: Color = Color.Unspecified) {}
      |"""
        .trimMargin()
    val joined = joinKotlinFiles(main, listOf(companion))
    assertEquals(
      """
      |// Screen.kt
      |package generated.uibuilder
      |
      |import androidx.compose.runtime.Composable
      |import androidx.compose.ui.unit.sp
      |import androidx.compose.ui.graphics.Color
      |
      |@Composable fun Screen() { A(fontSize = 1.sp) }
      |
      |// Generated by VariableFontCodegen: "Flex".
      |// Do not edit.
      |@Composable internal fun A(fontSize: TextUnit, color: Color = Color.Unspecified) {}
      |"""
        .trimMargin(),
      joined,
    )
    assertTrue(joinKotlinFiles(main, emptyList()) == main)
  }
}
